package sudokugame;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JTextField;

/**
 *
 * @author Anthony
 */
public class SudokuGUI extends javax.swing.JFrame {

    /**
     * Creates new form SudokuGUI
     */
    public SudokuGUI() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        final int VERTICAL_START = 135;
        final int HORIZONTAL_START = 85;
        final int WIDTH = 494;
        final int HEIGHT = 494;
        super.paint(g);
        Color c = new Color(151, 151, 151);
        g.setColor(c);
        g.fillRect(HORIZONTAL_START, VERTICAL_START + 162, WIDTH, 2);
        g.fillRect(HORIZONTAL_START, VERTICAL_START + 330, WIDTH, 2);
        g.fillRect(HORIZONTAL_START + 162, VERTICAL_START, 2, HEIGHT);
        g.fillRect(HORIZONTAL_START + 330, VERTICAL_START, 2, HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSolve = new javax.swing.JButton();
        buttonGenerate = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        square40 = new javax.swing.JTextField();
        square42 = new javax.swing.JTextField();
        square41 = new javax.swing.JTextField();
        square43 = new javax.swing.JTextField();
        square44 = new javax.swing.JTextField();
        square46 = new javax.swing.JTextField();
        square45 = new javax.swing.JTextField();
        square47 = new javax.swing.JTextField();
        square48 = new javax.swing.JTextField();
        square37 = new javax.swing.JTextField();
        square30 = new javax.swing.JTextField();
        square38 = new javax.swing.JTextField();
        square32 = new javax.swing.JTextField();
        square31 = new javax.swing.JTextField();
        square33 = new javax.swing.JTextField();
        square34 = new javax.swing.JTextField();
        square36 = new javax.swing.JTextField();
        square35 = new javax.swing.JTextField();
        square27 = new javax.swing.JTextField();
        square20 = new javax.swing.JTextField();
        square28 = new javax.swing.JTextField();
        square22 = new javax.swing.JTextField();
        square21 = new javax.swing.JTextField();
        square23 = new javax.swing.JTextField();
        square24 = new javax.swing.JTextField();
        square26 = new javax.swing.JTextField();
        square25 = new javax.swing.JTextField();
        square17 = new javax.swing.JTextField();
        square10 = new javax.swing.JTextField();
        square18 = new javax.swing.JTextField();
        square12 = new javax.swing.JTextField();
        square11 = new javax.swing.JTextField();
        square13 = new javax.swing.JTextField();
        square14 = new javax.swing.JTextField();
        square16 = new javax.swing.JTextField();
        square15 = new javax.swing.JTextField();
        square07 = new javax.swing.JTextField();
        square00 = new javax.swing.JTextField();
        square08 = new javax.swing.JTextField();
        square02 = new javax.swing.JTextField();
        square01 = new javax.swing.JTextField();
        square03 = new javax.swing.JTextField();
        square04 = new javax.swing.JTextField();
        square06 = new javax.swing.JTextField();
        square05 = new javax.swing.JTextField();
        square65 = new javax.swing.JTextField();
        square57 = new javax.swing.JTextField();
        square50 = new javax.swing.JTextField();
        square58 = new javax.swing.JTextField();
        square52 = new javax.swing.JTextField();
        square51 = new javax.swing.JTextField();
        square53 = new javax.swing.JTextField();
        square54 = new javax.swing.JTextField();
        square56 = new javax.swing.JTextField();
        square55 = new javax.swing.JTextField();
        square80 = new javax.swing.JTextField();
        square82 = new javax.swing.JTextField();
        square81 = new javax.swing.JTextField();
        square83 = new javax.swing.JTextField();
        square84 = new javax.swing.JTextField();
        square86 = new javax.swing.JTextField();
        square85 = new javax.swing.JTextField();
        square87 = new javax.swing.JTextField();
        square88 = new javax.swing.JTextField();
        square77 = new javax.swing.JTextField();
        square70 = new javax.swing.JTextField();
        square78 = new javax.swing.JTextField();
        square72 = new javax.swing.JTextField();
        square71 = new javax.swing.JTextField();
        square73 = new javax.swing.JTextField();
        square74 = new javax.swing.JTextField();
        square76 = new javax.swing.JTextField();
        square75 = new javax.swing.JTextField();
        square67 = new javax.swing.JTextField();
        square60 = new javax.swing.JTextField();
        square68 = new javax.swing.JTextField();
        square62 = new javax.swing.JTextField();
        square61 = new javax.swing.JTextField();
        square63 = new javax.swing.JTextField();
        square64 = new javax.swing.JTextField();
        square66 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Generator/Solver");

        buttonSolve.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        buttonSolve.setText("Solve");
        buttonSolve.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSolveActionPerformed(evt);
            }
        });

        buttonGenerate.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        buttonGenerate.setText("Generate");
        buttonGenerate.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateActionPerformed(evt);
            }
        });

        buttonClear.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("Welcome to the Sudoku Generator/Solver!");

        square40.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square40.setToolTipText(null);
        square40.setPreferredSize(new java.awt.Dimension(50, 50));

        square42.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square42.setToolTipText(null);
        square42.setPreferredSize(new java.awt.Dimension(50, 50));

        square41.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square41.setToolTipText(null);
        square41.setPreferredSize(new java.awt.Dimension(50, 50));

        square43.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square43.setToolTipText(null);
        square43.setPreferredSize(new java.awt.Dimension(50, 50));

        square44.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square44.setToolTipText(null);
        square44.setPreferredSize(new java.awt.Dimension(50, 50));

        square46.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square46.setToolTipText(null);
        square46.setPreferredSize(new java.awt.Dimension(50, 50));

        square45.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square45.setToolTipText(null);
        square45.setPreferredSize(new java.awt.Dimension(50, 50));

        square47.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square47.setToolTipText(null);
        square47.setPreferredSize(new java.awt.Dimension(50, 50));

        square48.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square48.setToolTipText(null);
        square48.setPreferredSize(new java.awt.Dimension(50, 50));

        square37.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square37.setToolTipText(null);
        square37.setPreferredSize(new java.awt.Dimension(50, 50));

        square30.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square30.setToolTipText(null);
        square30.setPreferredSize(new java.awt.Dimension(50, 50));

        square38.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square38.setToolTipText(null);
        square38.setPreferredSize(new java.awt.Dimension(50, 50));

        square32.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square32.setToolTipText(null);
        square32.setPreferredSize(new java.awt.Dimension(50, 50));

        square31.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square31.setToolTipText(null);
        square31.setPreferredSize(new java.awt.Dimension(50, 50));

        square33.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square33.setToolTipText(null);
        square33.setPreferredSize(new java.awt.Dimension(50, 50));

        square34.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square34.setToolTipText(null);
        square34.setPreferredSize(new java.awt.Dimension(50, 50));

        square36.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square36.setToolTipText(null);
        square36.setPreferredSize(new java.awt.Dimension(50, 50));

        square35.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square35.setToolTipText(null);
        square35.setPreferredSize(new java.awt.Dimension(50, 50));

        square27.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square27.setToolTipText(null);
        square27.setPreferredSize(new java.awt.Dimension(50, 50));

        square20.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square20.setToolTipText(null);
        square20.setPreferredSize(new java.awt.Dimension(50, 50));

        square28.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square28.setToolTipText(null);
        square28.setPreferredSize(new java.awt.Dimension(50, 50));

        square22.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square22.setToolTipText(null);
        square22.setPreferredSize(new java.awt.Dimension(50, 50));

        square21.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square21.setToolTipText(null);
        square21.setPreferredSize(new java.awt.Dimension(50, 50));

        square23.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square23.setToolTipText(null);
        square23.setPreferredSize(new java.awt.Dimension(50, 50));

        square24.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square24.setToolTipText(null);
        square24.setPreferredSize(new java.awt.Dimension(50, 50));

        square26.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square26.setToolTipText(null);
        square26.setPreferredSize(new java.awt.Dimension(50, 50));

        square25.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square25.setToolTipText(null);
        square25.setPreferredSize(new java.awt.Dimension(50, 50));

        square17.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square17.setToolTipText(null);
        square17.setPreferredSize(new java.awt.Dimension(50, 50));

        square10.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square10.setToolTipText(null);
        square10.setPreferredSize(new java.awt.Dimension(50, 50));

        square18.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square18.setToolTipText(null);
        square18.setPreferredSize(new java.awt.Dimension(50, 50));

        square12.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square12.setToolTipText(null);
        square12.setPreferredSize(new java.awt.Dimension(50, 50));

        square11.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square11.setToolTipText(null);
        square11.setPreferredSize(new java.awt.Dimension(50, 50));

        square13.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square13.setToolTipText(null);
        square13.setPreferredSize(new java.awt.Dimension(50, 50));

        square14.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square14.setToolTipText(null);
        square14.setPreferredSize(new java.awt.Dimension(50, 50));

        square16.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square16.setToolTipText(null);
        square16.setPreferredSize(new java.awt.Dimension(50, 50));

        square15.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square15.setToolTipText(null);
        square15.setPreferredSize(new java.awt.Dimension(50, 50));

        square07.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square07.setToolTipText(null);
        square07.setPreferredSize(new java.awt.Dimension(50, 50));

        square00.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square00.setToolTipText(null);
        square00.setPreferredSize(new java.awt.Dimension(50, 50));

        square08.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square08.setToolTipText(null);
        square08.setPreferredSize(new java.awt.Dimension(50, 50));

        square02.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square02.setToolTipText(null);
        square02.setPreferredSize(new java.awt.Dimension(50, 50));

        square01.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square01.setToolTipText(null);
        square01.setPreferredSize(new java.awt.Dimension(50, 50));

        square03.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square03.setToolTipText(null);
        square03.setPreferredSize(new java.awt.Dimension(50, 50));

        square04.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square04.setToolTipText(null);
        square04.setPreferredSize(new java.awt.Dimension(50, 50));

        square06.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square06.setToolTipText(null);
        square06.setPreferredSize(new java.awt.Dimension(50, 50));

        square05.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square05.setToolTipText(null);
        square05.setPreferredSize(new java.awt.Dimension(50, 50));

        square65.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square65.setToolTipText(null);
        square65.setPreferredSize(new java.awt.Dimension(50, 50));

        square57.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square57.setToolTipText(null);
        square57.setPreferredSize(new java.awt.Dimension(50, 50));

        square50.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square50.setToolTipText(null);
        square50.setPreferredSize(new java.awt.Dimension(50, 50));

        square58.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square58.setToolTipText(null);
        square58.setPreferredSize(new java.awt.Dimension(50, 50));

        square52.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square52.setToolTipText(null);
        square52.setPreferredSize(new java.awt.Dimension(50, 50));

        square51.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square51.setToolTipText(null);
        square51.setPreferredSize(new java.awt.Dimension(50, 50));

        square53.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square53.setToolTipText(null);
        square53.setPreferredSize(new java.awt.Dimension(50, 50));

        square54.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square54.setToolTipText(null);
        square54.setPreferredSize(new java.awt.Dimension(50, 50));

        square56.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square56.setToolTipText(null);
        square56.setPreferredSize(new java.awt.Dimension(50, 50));

        square55.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square55.setToolTipText(null);
        square55.setPreferredSize(new java.awt.Dimension(50, 50));

        square80.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square80.setToolTipText(null);
        square80.setPreferredSize(new java.awt.Dimension(50, 50));

        square82.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square82.setToolTipText(null);
        square82.setPreferredSize(new java.awt.Dimension(50, 50));

        square81.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square81.setToolTipText(null);
        square81.setPreferredSize(new java.awt.Dimension(50, 50));

        square83.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square83.setToolTipText(null);
        square83.setPreferredSize(new java.awt.Dimension(50, 50));

        square84.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square84.setToolTipText(null);
        square84.setPreferredSize(new java.awt.Dimension(50, 50));

        square86.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square86.setToolTipText(null);
        square86.setPreferredSize(new java.awt.Dimension(50, 50));

        square85.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square85.setToolTipText(null);
        square85.setPreferredSize(new java.awt.Dimension(50, 50));

        square87.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square87.setToolTipText(null);
        square87.setPreferredSize(new java.awt.Dimension(50, 50));

        square88.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square88.setToolTipText(null);
        square88.setPreferredSize(new java.awt.Dimension(50, 50));

        square77.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square77.setToolTipText(null);
        square77.setPreferredSize(new java.awt.Dimension(50, 50));

        square70.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square70.setToolTipText(null);
        square70.setPreferredSize(new java.awt.Dimension(50, 50));

        square78.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square78.setToolTipText(null);
        square78.setPreferredSize(new java.awt.Dimension(50, 50));

        square72.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square72.setToolTipText(null);
        square72.setPreferredSize(new java.awt.Dimension(50, 50));

        square71.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square71.setToolTipText(null);
        square71.setPreferredSize(new java.awt.Dimension(50, 50));

        square73.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square73.setToolTipText(null);
        square73.setPreferredSize(new java.awt.Dimension(50, 50));

        square74.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square74.setToolTipText(null);
        square74.setPreferredSize(new java.awt.Dimension(50, 50));

        square76.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square76.setToolTipText(null);
        square76.setPreferredSize(new java.awt.Dimension(50, 50));

        square75.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square75.setToolTipText(null);
        square75.setPreferredSize(new java.awt.Dimension(50, 50));

        square67.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square67.setToolTipText(null);
        square67.setPreferredSize(new java.awt.Dimension(50, 50));

        square60.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square60.setToolTipText(null);
        square60.setPreferredSize(new java.awt.Dimension(50, 50));

        square68.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square68.setToolTipText(null);
        square68.setPreferredSize(new java.awt.Dimension(50, 50));

        square62.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square62.setToolTipText(null);
        square62.setPreferredSize(new java.awt.Dimension(50, 50));

        square61.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square61.setToolTipText(null);
        square61.setPreferredSize(new java.awt.Dimension(50, 50));

        square63.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square63.setToolTipText(null);
        square63.setPreferredSize(new java.awt.Dimension(50, 50));

        square64.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square64.setToolTipText(null);
        square64.setPreferredSize(new java.awt.Dimension(50, 50));

        square66.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        square66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square66.setToolTipText(null);
        square66.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(134, 136, 140));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Anthony Howell 2021");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(buttonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buttonSolve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(square08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(square88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSolve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(square08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(labelMessage)
                .addGap(2, 2, 2)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        //Store all the textFields
        JTextField textFields[][] = {
            {square00, square01, square02, square03, square04, square05, square06, square07, square08},
            {square10, square11, square12, square13, square14, square15, square16, square17, square18},
            {square20, square21, square22, square23, square24, square25, square26, square27, square28},
            {square30, square31, square32, square33, square34, square35, square36, square37, square38},
            {square40, square41, square42, square43, square44, square45, square46, square47, square48},
            {square50, square51, square52, square53, square54, square55, square56, square57, square58},
            {square60, square61, square62, square63, square64, square65, square66, square67, square68},
            {square70, square71, square72, square73, square74, square75, square76, square77, square78},
            {square80, square81, square82, square83, square84, square85, square86, square87, square88}
        };
        
        //Reset the gameboard to 0s and the textFields to ""
        for (int x = 0; x < gameboard.length; x++){
            for (int y = 0; y < gameboard.length; y++){
                gameboard[x][y] = 0;
                textFields[x][y].setText("");
            }
        }
        
        labelMessage.setText("Board cleared!");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSolveActionPerformed
        //Store all the textFields
        JTextField textFields[][] = {
            {square00, square01, square02, square03, square04, square05, square06, square07, square08},
            {square10, square11, square12, square13, square14, square15, square16, square17, square18},
            {square20, square21, square22, square23, square24, square25, square26, square27, square28},
            {square30, square31, square32, square33, square34, square35, square36, square37, square38},
            {square40, square41, square42, square43, square44, square45, square46, square47, square48},
            {square50, square51, square52, square53, square54, square55, square56, square57, square58},
            {square60, square61, square62, square63, square64, square65, square66, square67, square68},
            {square70, square71, square72, square73, square74, square75, square76, square77, square78},
            {square80, square81, square82, square83, square84, square85, square86, square87, square88}
        };
        
        //Parse the textfields into the gameboard
        for (int x = 0; x < gameboard.length; x++){
            for (int y = 0; y < gameboard.length; y++){
                int value;
                        
                //Convert null textFields into 0s
                if (textFields[x][y].getText().equals("")){
                    value = 0;
                } 
                //If not, try to convert the string to an int
                else try {
                    value = Integer.parseInt(textFields[x][y].getText());
                    
                    if (value < 1 || value > 9){
                        //Input error: value is not in the range of 1-9
                        labelMessage.setText("Error! Invalid input at (" + (x + 1) + "," + (y + 1) + ")!");
                        return;
                    }
                } catch (NumberFormatException ex){
                    //Input error: display error text and abort
                    labelMessage.setText("Error! Invalid input at (" + (x + 1) + "," + (y + 1) + ")!");
                    return;
                }
                
                gameboard[x][y] = value;
            }
        }
        
        //Check if board is empty
        if (SudokuGame.checkBoardEmpty(gameboard)){
            labelMessage.setText("Error! Board is empty!");
            return;
        }
        
        //Check is board has any pre-filled invalid moves
        for (int x = 0; x < gameboard.length; x++) {
            for (int y = 0; y < gameboard.length; y++) {
                //If there exists an illegal move, return false
                if (gameboard[x][y] != 0){
                    if (!SudokuGame.checkMoveValid(x, y, gameboard, gameboard[x][y])) {
                        labelMessage.setText("Error! Invalid input at (" + (x + 1) + "," + (y + 1) + ")!");
                        return;
                    }
                }
            }
        }
        
        //Attempt to solve the gameboard
        SudokuGame.generateBoard(gameboard);
        
        //If a solution was found, update the display
        if (SudokuGame.checkBoardSolved(gameboard)){
            labelMessage.setText("Solution found!");
            
            for (int x = 0; x < gameboard.length; x++){
                for (int y = 0; y < gameboard.length; y++){
                    textFields[x][y].setText(String.valueOf(gameboard[x][y]));
                }
            }
        } 
        //If not, display that the puzzle is unsolvable
        else {
            labelMessage.setText("Puzzle is unsolvable!");
        }
    }//GEN-LAST:event_buttonSolveActionPerformed

    private void buttonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateActionPerformed
        //Store all the textFields
        JTextField textFields[][] = {
            {square00, square01, square02, square03, square04, square05, square06, square07, square08},
            {square10, square11, square12, square13, square14, square15, square16, square17, square18},
            {square20, square21, square22, square23, square24, square25, square26, square27, square28},
            {square30, square31, square32, square33, square34, square35, square36, square37, square38},
            {square40, square41, square42, square43, square44, square45, square46, square47, square48},
            {square50, square51, square52, square53, square54, square55, square56, square57, square58},
            {square60, square61, square62, square63, square64, square65, square66, square67, square68},
            {square70, square71, square72, square73, square74, square75, square76, square77, square78},
            {square80, square81, square82, square83, square84, square85, square86, square87, square88}
        };
        
        //Generate a puzzle out of a gameboard
        gameboard = SudokuGame.generatePuzzle(SudokuGame.generateBoard());
        
        //Set the gameboard to match the result;
        for (int x = 0; x < gameboard.length; x++){
            for (int y = 0; y < gameboard.length; y++){
                if (gameboard[x][y] != 0){
                    textFields[x][y].setText(String.valueOf(gameboard[x][y]));
                } else {
                    textFields[x][y].setText("");
                }
                
            }
        }
        
        labelMessage.setText("Puzzle generated!");
    }//GEN-LAST:event_buttonGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SudokuGUI().setVisible(true);
        });
    }
    
    //Declare variables
    int[][] gameboard = new int[9][9];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonGenerate;
    private javax.swing.JButton buttonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JTextField square00;
    private javax.swing.JTextField square01;
    private javax.swing.JTextField square02;
    private javax.swing.JTextField square03;
    private javax.swing.JTextField square04;
    private javax.swing.JTextField square05;
    private javax.swing.JTextField square06;
    private javax.swing.JTextField square07;
    private javax.swing.JTextField square08;
    private javax.swing.JTextField square10;
    private javax.swing.JTextField square11;
    private javax.swing.JTextField square12;
    private javax.swing.JTextField square13;
    private javax.swing.JTextField square14;
    private javax.swing.JTextField square15;
    private javax.swing.JTextField square16;
    private javax.swing.JTextField square17;
    private javax.swing.JTextField square18;
    private javax.swing.JTextField square20;
    private javax.swing.JTextField square21;
    private javax.swing.JTextField square22;
    private javax.swing.JTextField square23;
    private javax.swing.JTextField square24;
    private javax.swing.JTextField square25;
    private javax.swing.JTextField square26;
    private javax.swing.JTextField square27;
    private javax.swing.JTextField square28;
    private javax.swing.JTextField square30;
    private javax.swing.JTextField square31;
    private javax.swing.JTextField square32;
    private javax.swing.JTextField square33;
    private javax.swing.JTextField square34;
    private javax.swing.JTextField square35;
    private javax.swing.JTextField square36;
    private javax.swing.JTextField square37;
    private javax.swing.JTextField square38;
    private javax.swing.JTextField square40;
    private javax.swing.JTextField square41;
    private javax.swing.JTextField square42;
    private javax.swing.JTextField square43;
    private javax.swing.JTextField square44;
    private javax.swing.JTextField square45;
    private javax.swing.JTextField square46;
    private javax.swing.JTextField square47;
    private javax.swing.JTextField square48;
    private javax.swing.JTextField square50;
    private javax.swing.JTextField square51;
    private javax.swing.JTextField square52;
    private javax.swing.JTextField square53;
    private javax.swing.JTextField square54;
    private javax.swing.JTextField square55;
    private javax.swing.JTextField square56;
    private javax.swing.JTextField square57;
    private javax.swing.JTextField square58;
    private javax.swing.JTextField square60;
    private javax.swing.JTextField square61;
    private javax.swing.JTextField square62;
    private javax.swing.JTextField square63;
    private javax.swing.JTextField square64;
    private javax.swing.JTextField square65;
    private javax.swing.JTextField square66;
    private javax.swing.JTextField square67;
    private javax.swing.JTextField square68;
    private javax.swing.JTextField square70;
    private javax.swing.JTextField square71;
    private javax.swing.JTextField square72;
    private javax.swing.JTextField square73;
    private javax.swing.JTextField square74;
    private javax.swing.JTextField square75;
    private javax.swing.JTextField square76;
    private javax.swing.JTextField square77;
    private javax.swing.JTextField square78;
    private javax.swing.JTextField square80;
    private javax.swing.JTextField square81;
    private javax.swing.JTextField square82;
    private javax.swing.JTextField square83;
    private javax.swing.JTextField square84;
    private javax.swing.JTextField square85;
    private javax.swing.JTextField square86;
    private javax.swing.JTextField square87;
    private javax.swing.JTextField square88;
    // End of variables declaration//GEN-END:variables

}
